# Working solution courtesy of https://github.com/kharus at https://github.com/kharus/sigma-hack
# https://youtrack.jetbrains.com/issue/QD-6587/Qodana-ignores-maven-setup-on-github
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Unit test with Maven
        run: |
          mvn -B test-compile --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # read the steps about it below
        with:
          args: -u,root
